model_name_or_path: "unsloth/llama-3-8b-instruct"
dataset_path: "outputs/sample_output.jsonl"
attention_impl: "flash_attention_2"
trainer:
  output_dir: "outputs/llama-3-8b-instruct-restem"
  do_train: true
  eval_strategy: "no"
  per_device_train_batch_size: 8
  gradient_accumulation_steps: 4
  learning_rate: 2e-5
  num_train_epochs: 5
  lr_scheduler_type: "cosine"
  warmup_ratio: 0.2
  logging_strategy: "steps"
  logging_steps: 1
  save_strategy: "epoch"
  fp16: false
  bf16: true
  run_name: "llama-3-8b-instruct"
  group_by_length: true
  report_to: "wandb"
  deepspeed: "configs/deepspeed_config.json"
